<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.0 target.glb
-->

<script lang='ts'>
  import * as THREE from 'three'
	import { T, forwardEventHandlers, useFrame } from '@threlte/core'
	import { useGltf } from '@threlte/extras'

	export const ref = new THREE.Group()

  let prop: THREE.Object3D

	const gltf = useGltf('/target.glb')

	const component = forwardEventHandlers()

  let time = 0
  useFrame((_, delta) => {
    time += delta
    if (!prop) return
    prop.rotation.y -= 0.2
    ref.position.x = Math.sin(time) / 2
    ref.position.y = (Math.cos(time) / 2) + 0.5
    ref.position.z = THREE.MathUtils.clamp(Math.tan(time) / 8, -7, 7)
  })
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Mesh geometry={gltf.nodes.Target_1.geometry} material={gltf.materials['Material.001']} />
		<T.Mesh
			geometry={gltf.nodes.Target_3.geometry}
			material={gltf.materials['Material.002']}
			position={[0, 0, -0.01]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Target_4.geometry}
			material={gltf.nodes.Target_4.material}
			position={[0, 0, -0.01]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Pole.geometry}
			material={gltf.materials['Material.003']}
			position={[0, 0, -0.07]}
		/>
		<T.Mesh geometry={gltf.nodes.Target_2.geometry} material={gltf.nodes.Target_2.material} />
		<T.Mesh
      bind:ref={prop}
			geometry={gltf.nodes.Prop.geometry}
			material={gltf.materials['Material.003']}
			position={[0, 0.25, -0.05]}
		/>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
